module DatosCentrosHelper
	DISCIPLINAS = [
		'Agronomía y especialidades silvoagropecuarias',
		'Álgebra',
		'Análisis',
		'Análisis de Señales',
		'Anatomía normal y patológica',
		'Anestesiologa, reanimación, tratamiento',
		'Antropología Cultural y Social',
		'Antropología Física',
		'Arqueología',
		'Astronomía',
		'Biofísica',
		'Biogeografía',
		'Biología celular',
		'Biología de poblaciones',
		'Biología del desarrollo',
		'Biología marina',
		'Biología molecular',
		'Bioquímica',
		'Bioquimica farmacología',
		'Biotecnología',
		'Botánica',
		'Cambio Social y Desarrollo',
		'Cardiología, fisiología cardiovascular',
		'Ciencias de Sistemas Complejos',
		'Ciencias del suelo',
		'Ciencias Matemáticas',
		'Ciencias Políticas',
		'Ciencias veterinarias',
		'Cirugia, traumatología, cirugía experimental',
		'Derecho',
		'Derecho Comercial, Industrial y Minero',
		'Derecho Comparado',
		'Derecho del Ambiente',
		'Derecho del Trabajo',
		'Derecho Económico',
		'Derecho Internacional Público y Privado',
		'Derecho Penal',
		'Derecho Privado',
		'Derecho Procesal',
		'Derecho Público',
		'Derecho Romano',
		'Dermatología y enfermedades de transmisión',
		'Desarrollo Económico',
		'Ecología y ciencias ambientales',
		'Econometría',
		'Economía',
		'Economía agraria y sistemas de producción',
		'Economía de Empresas',
		'Economía de Sectores Sociales',
		'Economía Industrial',
		'Economía Internacional',
		'Economía Laboral y de los Recursos Humanos',
		'Economía Monetaria',
		'Edafología',
		'Electrodinámica',
		'Electromagnetismo',
		'Enfermedades de la nutrición y endocrinología',
		'Enfermedades infecciosas, bacteriología',
		'Enfermedades respiratorias, fisiología',
		'Enfermedades veterinarias',
		'Enfermería, educación en salud',
		'Entomología',
		'Entomología agrícola',
		'Estadística',
		'Estructura del Mercado (Análisis del Funcionamiento del Mercado)'
		'Etnología',
		'Farmacia, farmacología clínica, laboratotio',
		'Farmacología',
		'Filosofía Política',
		'Finanzas',
		'Física',
		'Física atómica y molecular',
		'Física de fluidos',
		'Física de partículas elementales',
		'Física de plasmas',
		'Física de sólidos',
		'Física de superficies',
		'Física nuclear',
		'Físco-química',
		'Fisiología biofísica',
		'Fisiología vegetal',
		'Fisiopatología, fisiología clínica general'.
		'Fitopatología',
		'Fitotecnia',
		'Fruticultura y viticultura',
		'Gastroenterología, fisiología digestiva',
		'Genética y evolución',
		'Geodesia',
		'Geofísica',
		'Geografía',
		'Geografía Humana',
		'Geología y mineralogía',
		'Geometría',
		'Geoquímica',
		'Ginecología, obstetricia y reproducción',
		'Glaciología',
		'Hematología e inmunología clínica',
		'Hidrogeología',
		'Hidrología',
		'Higiene y salud pública (epidemiología,',
		'Histología',
		'Historia',
		'Historia y Filosofía del Derecho',
		'Horticultura',
		'Idiomas Específicos',
		'Informática',
		'Ingeniería',
		'Ingeniería aeronáutica',
		'Ingeniería agrícola',
		'Ingeniería biomédica y bioingeniería',
		'Ingeniería de construcción',
		'Ingeniería de instrumentación y control',
		'Ingeniería de materiales',
		'Ingeniería de minas',
		'Ingeniería de transportes',
		'Ingeniería del petroleo',
		'Ingeniería del viento y aerodinámica industrial',
		'Ingeniería eléctrica (incluyendo potencia)',
		'Ingeniería electrónica',
		'Ingeniería en computación',
		'Ingeniería en telecomunicaciones',
		'Ingeniería estructural (incluye ingeniería anatocismos)',
		'Ingeniería forestal',
		'Ingeniería genética',
		'Ingeniería geotécnica y afines',
		'Ingeniería hidráulica',
		'Ingeniería industrial y de sistemas',
		'Ingeniería Matemática',
		'Ingeniería mecánica',
		'Ingeniería mecatrónica',
		'Ingeniería metalúrgica',
		'Ingeniería naval',
		'Ingeniería nuclear',
		'Ingeniería oceánica',
		'Ingeniería química',
		'Ingeniería sanitaria',
		'Ingeniería textil',
		'Inmunología',
		'Limnología',
		'Lógica y fundamentos de las matemáticas',
		'Matemáticas del uso de los recursos',
		'Mecánica cuántica',
		'Mecánica estadística',
		'Medicina física y rehabilitación, kinesiología',
		'Medicina interna, patología humana',
		'Medicina legal',
		'Medicina nuclear, radioterapia',
		'Medicina psicosomática (incluyendo psiquiatría)',
		'Meteorología y climatología',
		'Metodología',
		'Métodos numéricos y computación',
		'Microbiología',
		'Morfología',
		'Nefrología, fisiología renal',
		'Neurología y neurocirugía',
		'Nutrición básica',
		'Nutrición vegetal, fertilización de cultivos',
		'Oceanografía',
		'Odontología, estomatología y cirugía maxilar',
		'Oftalmología',
		'Oncología, quimioterapia, cirugía oncológica',
		'Óptica cuántica',
		'Otorrinolaringología',
		'Otras especialidades de ciencias de la tierra',
		'Otras especialidades de ciencias de la Antropología',
		'Otras especialidades de la biolgía',
		'Otras especialidades de la Economía',
		'Otras especialidades de la física',
		'Otras especialidades de la ingeniería',
		'Otras especialidades de la medicina',
		'Otras especialidades de la química',
		'Otras especialidades de las matemáticas',
		'Otras especialidades del Derecho',
		'Otras Sicologías',
		'Otras Sociologías',
		'Paleobiología',
		'Paleontología',
		'Parasitología',
		'Pedagofía y Educación',
		'Pediatría, perinatología, fisiología pediátrica',
		'Periodismo',
		'Pesca y piscicultura',
		'Probabilidades, matemáticas aplicadas y estadísticas',
		'Procesamiento y tecnología de alimentos',
		'Producción animal',
		'Propagación de plantas',
		'Química analítica',
		'Química de recursos naturales',
		'Química del ambiente',
		'Química inorgánica',
		'Química nuclear',
		'Química orgánica',
		'Radiología y diagnóstico por imágenes',
		'Relatividad general y cosmología',
		'Reumatología, inflamación, enfermedades',
		'Sicobiología',
		'Sicología Clínica',
		'Sicología de la Educación y Cognitiva',
		'Sicología de la personalidad',
		'Sicología Experimental',
		'Sicología Laboral y Organizacional',
		'Sicología Social',
		'Sismología',
		'Sistemas dinámicos',
		'Sistemas no lineales',
		'Sociología',
		'Sociología de las organizaciones formales',
		'Sociología del Trabajo',
		'Sociología Urbana y Rural',
		'Tecnología de la madera',
		'Tectónica',
		'Teoría de los números',
		'Teoría Económica',
		'Teoría Socio Cultural',
		'Topología',
		'Toxicología',
		'Urbanismo',
		'Urología, transplante renal, fisiología',
		'Virología',
		'Zoología'
	]
end