module ListasGeneralesHelper
	def lgen_regiones
		[
			'Arica y Parinacota',
			'Tarapacá',
			'Antofagasta',
			'Atacama',
			'Coquimbo',
			'Valparaiso',
			'Libertador General Bernardo O\'Higgins',
			'Maule',
			'Bío Bío',
			'de la Araucanía',
			'de los Lagos',
			'Aisén del General Carlos Ibañez del Campo',
			'Magallanes y Antártica Chilena',
			'Metropolitana de Santiago',
			'de los Rios'
		]
	end

	def lgen_nacionalidades
		[
			'Afgano',
			'Albanés',
			'Alemán',
			'Americano / Noreteamericano',
			'Andorrano',
			'Angoleño',
			'Anguilense',
			'Antiguano',
			'Antillano holandés',
			'Argelino',
			'Argentino',
			'Armenio',
			'Arubeño',
			'Australiano',
			'Austríaco',
			'Azerbaiyano, Azerí',
			'Bahamés, Bahameño',
			'Bahreini',
			'Bangladesí',
			'Barbadense, Barbadiño',
			'Belga',
			'Beliceño',
			'Beninés',
			'Bermudeño',
			'Bielorruso',
			'Birmano',
			'Boliviano',
			'Bosnio, Bosnioherzegovino',
			'Botsuano',
			'Brasileño',
			'Británico',
			'Bruneano',
			'Búlgaro',
			'Burkinés',
			'Burundés',
			'Butanés',
			'Caboverdiano',
			'Caimanés',
			'Camboyabo/na',
			'Camerunés',
			'Canadiense',
			'Centroafricano',
			'Chadiano',
			'Checo',
			'Chileno',
			'Chino',
			'Chipriota',
			'Cingalés, Esrilanqués',
			'Colombiano',
			'Comorense',
			'Congolés, Congoleño',
			'Costarricense',
			'Croata',
			'Cubano',
			'Curazaleño',
			'Danés',
			'Djibutí, Djibutiense',
			'Dominicano',
			'Dominiqués',
			'Ecuatoguineano',
			'Ecuatoriano',
			'Egipcio',
			'Emiratí',
			'Eritreo',
			'Escocés',
			'Eslovaco',
			'Esloveno',
			'Español',
			'Estonio',
			'Etíope',
			'Feroés',
			'Filipino',
			'Finlandés',
			'Fiyiano',
			'Francés',
			'Gabonés',
			'Galés',
			'Gambiano',
			'Georgiano',
			'Gerogiano',
			'Ghanés',
			'Gibraltareño',
			'Granadino',
			'Griego',
			'Guamés',
			'Guatemalteco',
			'Guerneseyés',
			'Guineano',
			'Guyanés',
			'Haitiano',
			'Holandés',
			'Hondureño',
			'Húngaro',
			'Indio',
			'Indonesio',
			'Iraní / persa',
			'Iraquí',
			'Irlandés',
			'Islandes',
			'Israelí',
			'Italiano',
			'Jamaicano',
			'Japonés',
			'Jerseyés',
			'Jordano',
			'Kasajo, Kasako',
			'Keniano',
			'Kirguís, Kirguiso',
			'Kiribatiano',
			'Kosovar',
			'Kuwaití',
			'Laosiano',
			'Lesotense',
			'Letón',
			'Libanés',
			'Liberiano',
			'Libio',
			'Liechtensteiniano',
			'Lituano',
			'Luxemburgués',
			'Macaense',
			'Macedonio',
			'Malasio',
			'Malauí',
			'Maldivo',
			'Malgache',
			'Maliense, Malí',
			'Maltés',
			'Malvinense',
			'Marfileño',
			'Marroquí',
			'Marshalés',
			'Mauriciano',
			'Mauritano',
			'Mexicano',
			'Micronesio',
			'Moldavo',
			'Monegasco',
			'Mongol',
			'Montenegrino',
			'Montserratense',
			'Mozambiqueño',
			'Namibio',
			'Nauruano',
			'Neerlandés',
			'Neozelandés',
			'Nepalés',
			'Nicaraguense',
			'Nigeriano',
			'Nigerino',
			'Niueño',
			'Norcoreano',
			'Noruego',
			'Omaní, Omanés',
			'Otra',
			'Palauano',
			'Palestino',
			'Panameño',
			'Papú, Papúano',
			'Paquistaní',
			'Paraguayo',
			'Peruano',
			'Polaco',
			'Portugués',
			'Puertoriqueño',
			'Qatarí, Catarí',
			'Ruandés',
			'Rumano',
			'Ruso',
			'Saharaui',
			'Salomonense, Salomon',
			'Salvadoreño',
			'Samoano',
			'Sancristobaleño',
			'Santalucense',
			'Santotomense',
			'Sanvicentino',
			'Saudí',
			'Senegalés',
			'Serbio',
			'Seychellense',
			'Sierraleonés',
			'Singapurense',
			'Sirio',
			'Somalí',
			'Suazi',
			'Sudafricano',
			'Sudanés',
			'Sueco',
			'Suizo',
			'Surcoreano',
			'Surinamés',
			'Sursudanés',
			'Tailandés',
			'Taiwanés',
			'Tanzano',
			'Tayiko',
			'Timorense',
			'Togolés',
			'Tongano',
			'Trinitense, Tobaguense',
			'Tunecino',
			'Turco',
			'Turcomano',
			'Tuvaluano',
			'Ucraniano',
			'Ugandés',
			'Uruguayo',
			'Uzbeko',
			'Vanuatuense',
			'Venezolano',
			'Vietnamita',
			'Yemení, Yemenita',
			'Yibutiano',
			'Zambio, Zambés, Zambeño',
			'Zimbabuense'
		]
	end

	def lgen_profesiones
		[
			'Administración de Empresas',
			'Administración Pública',
			'Agronomía',
			'Antropología',
			'Arqueología',
			'Arquitectura',
			'Astronomía',
			'Auditoría',
			'Bibliotecología',
			'Bioingeniería',
			'Biología',
			'Biología Marina',
			'Bioquímica',
			'Biotecnología',
			'Ciencias Políticas',
			'Cine',
			'Comunicación',
			'Comunicación Audiovisual',
			'Construcción Civil',
			'Contabilidad',
			'Derecho',
			'Diseño',
			'Diseño Gráfico',
			'Diseño Industrial',
			'Ecología Marina',
			'Economía',
			'Educación Básica',
			'Educación Media',
			'Educación Diferencial',
			'Educación Física',
			'Educación Parvularia',
			'Enfermería',
			'Estadística',
			'Filosofía',
			'Física',
			'Fonoaudiología',
			'Geofísica',
			'Geología',
			'Historia',
			'Informática',
			'Ingeniería',
			'Ingeniería Agronómica',
			'Ingeniería Ambiental',
			'Ingeniería Civil',
			'Ingeniería comercial',
			'Ingeniería de Ejecución',
			'Estudios internacionales',
			'Kinesiología',
			'Literatura',
			'Matemáticas',
			'Medicina',
			'Medicina Veterinaria',
			'Meteorología',
			'Nutrición',
			'Obstetricia',
			'Oceanografía',
			'Odontología',
			'Pedagogía',
			'Periodismo',
			'Psicología',
			'Psicopedagogía',
			'Psiquiatría',
			'Publicidad',
			'Química',
			'Química y Farmacia',
			'Relaciones Públicas',
			'Sociología',
			'Tecnología Médica',
			'Teología',
			'Terapia Ocupacional',
			'Topografía',
			'Trabajo Social',
			'Traducción',
			'Turismo',
			'Otra'
		]
	end

	def lgen_relacion_centro
		[
			'Full Time',
			'Part Time'
		]
	end

	def lgen_paises
		[
			'Abganistán',
			'Albania',
			'Alemania',
			'Andorra',
			'Angola',
			'Anguila',
			'Antigua y Barbuda',
			'Antillas Holandesas',
			'Arabia Saudita',
			'Argelia',
			'Argentina',
			'Armenia',
			'Aruba',
			'Australia',
			'Austria',
			'Azerbaiján',
			'Bahamas, Las',
			'Bahréin',
			'Bangladesh',
			'Barbados',
			'Bélgica',
			'Belice',
			'Benín',
			'Bermudas',
			'Bielorrusia',
			'Birmania (Myanmar',
			'Bolivia',
			'Bosnia y Herzegovina',
			'Botswana',
			'Brasil',
			'Brunéi',
			'Bulgaria',
			'Burkina Faso',
			'Burundi',
			'Bután',
			'Cabo Verde',
			'Cambodia',
			'Camerún',
			'Canadá',
			'Chad',
			'Chile',
			'China',
			'Chipre	',
			'Colombia',
			'Comoras',
			'Corea del Norte',
			'Corea del Sur',
			'Costa de Marfil',
			'Costa Rica',
			'Croacia',
			'Cuba',
			'Curazao',
			'Dinamarca',
			'Djibouti',
			'Dominica',
			'Ecuador',
			'Egipto',
			'El Congo',
			'El Líbano',
			'El Salvador',
			'Emiratos Árabes Unidos',
			'Eritrea',
			'Escocia',
			'Eslovaquia',
			'Eslovenia',
			'España',
			'Estados Unidos de America',
			'Estonia',
			'Etiopía',
			'Federación de San Cristobal y Nieves',
			'Fiji',
			'Filipinas',
			'Finlandia',
			'Francia',
			'Gabón',
			'Gales',
			'Gambia',
			'Georgia',
			'Ghana',
			'Gibraltar',
			'Granada',
			'Grecia',
			'Guam',
			'Guatemala',
			'Guernsey',
			'Guinea',
			'Guinea Ecuatorial',
			'Guyana',
			'Haití',
			'Holanda/Países Bajos',
			'Honduras',
			'Hungría',
			'India',
			'Indonesia',
			'Inglaterra',
			'Irak',
			'Irán',
			'Irlanda',
			'Isla Mauricio',
			'Islandia',
			'Islas Caimán',
			'Islas Feroe',
			'Islas Malvinas',
			'Islas Marshall',
			'Islas Salomón',
			'Israel',
			'Italia',
			'Jamaica',
			'Japón',
			'Jersey',
			'Jordania',
			'Kazajistán',
			'Kenia',
			'Kirguistán',
			'Kiribati',
			'Kosovo',
			'Kuwait',
			'Laos',
			'Lesoto',
			'Letonia',
			'Liberia',
			'Libia',
			'Liechtenstein',
			'Lituania',
			'Luxemburgo',
			'Macao',
			'Macedonia',
			'Madagascar',
			'Malasia',
			'Malaui',
			'Maldivas, Las',
			'Mali',
			'Malta',
			'Marruecos',
			'Mauritania',
			'México',
			'Micronesia',
			'Moldavia',
			'Mónaco',
			'Mongolia',
			'Montserrat',
			'Montenegro',
			'Mozambique',
			'Namibia',
			'Nauru',
			'Nepal',
			'Nicaragua',
			'Níger',
			'Nigeria',
			'Niue',
			'Noruega',
			'Nueva Zelandia',
			'Omán',
			'Otro',
			'Pakistán',
			'Palaos',
			'Palestina',
			'Panamá',
			'Papúa Nueva Guinea',
			'Paraguay',
			'Perú',
			'Polonia',
			'Portugal',
			'Puerto Rico',
			'Qatar',
			'Reino de los Países Bajos',
			'República Árabe Saharaui Democrática',
			'República Centroafricana',
			'República Checa',
			'República del Congo',
			'República Democrática de Santo Tomé y Príncipe',
			'República Democrática del Congo',
			'República Dominicana',
			'Ruanda',
			'Rumania',
			'Rusia',
			'Samoa',
			'San Vicente y las Granadinas',
			'Santa Lucía',
			'Senegal',
			'Serbia',
			'Seychelles',
			'Sierra Leona',
			'Singapur',
			'Siria',
			'Somalia',
			'Sri Lanka',
			'Suazilandia',
			'Sudáfrica',
			'Sudán',
			'Sudán del Sur',
			'Suecia',
			'Suiza',
			'Surinam',
			'Tailandia',
			'Taiwan',
			'Tajikistan',
			'Tanzania',
			'Timor Oriental',
			'Togo',
			'Tonga',
			'Trinidad y Tobago',
			'Túnez',
			'Turkmenistán',
			'Turquía',
			'Tuvalu',
			'Ucrania',
			'Uganda',
			'Uruguay',
			'Uzbekistán',
			'Vanuatu',
			'Venezuela',
			'Vietnam',
			'Yemen',
			'Yibuti',
			'Zambia',
			'Zimbabwe'
		]
	end

	def lgen_universidades
		[
			'CENTRO DE COMUNICACIÓN Y CULTURA PARA EL DESARROLLO',
			'CENTRO DE ESTUDIOS AVANZADOS EN ZONAS ÁRIDAS (CEAZA)',
			'CENTRO DE ESTUDIOS CIENTÍFICOS',
			'CENTRO DE ESTUDIOS DE LA MUJER',
			'CENTRO DE ESTUDIOS DE LA REALIDAD CONTEMPORÁNEA',
			'CENTRO DE ESTUDIOS PARA EL DESARROLLO DE LA MUJER',
			'CENTRO DE ESTUDIOS PARA EL DESARROLLO',
			'CENTRO DE GENÓMICA NUTRICIONAL AGRO ACUÍCOLA (CGNA)',
			'CENTRO DE INFORMACIÓN TECNOLÓGICA',
			'CENTRO DE INGENIERÍA DE LA INNOVACIÓN (CIN)',
			'CENTRO DE INVESTIGACIÓN CIENTÍFICO TECNOLÓGICO PARA LA MINERÍA (CICITEM)',
			'CENTRO DE INVESTIGACIÓN DE POLÍMEROS AVANZADOS (CIPA)',
			'CENTRO DE INVESTIGACIÓN EN ECOSISTEMAS DE LA PATAGONIA (CIEP)',
			'CENTRO DE INVESTIGACIÓN EN NUTRICIÓN, TECNOLOGÍA DE ALIMENTOS Y SUSTENTABILIDAD (CIEN AUTRAL)',
			'CENTRO DE INVESTIGACIÓN DE LA REALIDAD SOCIAL',
			'CENTRO DE INVESTIGACIÓN MINERA Y METALÚRGICA (CIMM)',
			'CENTRO DE INVESTIGACIÓN SOCIOCULTURAL BBELARMINO',
			'CENTRO LATINOAMERICANO DE ECONOMÍA Y POLÍTICA INTERNACIONAL',
			'CENTRO REGIONAL DE ESTUDIOS EN ALIMENTOS SALUDABLES (CREAS)',
			'CENTRO REGIONAL DE INVESTIGACIÓN Y DESARROLLO SUSTENTABLE DE ATACAMA (CRIDESAT)',
			'COMISIÓN CHILENA DE ENERGÍA NUCLEAR',
			'CORPORACIÓN REGIONAL DE DESARROLLO CIENTÍFICO Y TECNOLÓGICO DEL HOMBRE EN EL DESIERTO (CODECITE)',
			'CORPORACIÓN INVESTIGACIÓN ECONÓMICA PARA LATINOAMERICA',
			'FACUTAD LATINOAMERICANA DE CIENCIAS SOCIALES',
			'FUNDACIÓN CENTRO DE ESTUDIOS DEL CUATERNARIO DE FUEGO-PATAGONIA Y ANTÁRTICA (CEQUA)',
			'FUNDACIÓN CIENCIA PARA LA VIDA',
			'FUNDACIÓN OMORA',
			'FUNDACIÓN SENDA DARWIN',
			'iNSTITUTO ANTÁRTICO CHILENO',
			'INSTITUTO CHILENO DE MEDICINA REPRODUCTIVA',
			'INSTITUTO DE DINÁMICA CELULAR Y BIOTECNOLOGÍA',
			'INSTITUTO DE ECOLOGÍA Y BIODIVERSIDAD',
			'INSTITUTO DE ESTUDIOS MÉDICOS AVANZADOS',
			'INSTITUTO DE FOMENTO PESQUERO IFOP',
			'iNSTITUTO DE INVESTIGACIÓN PESQUERA',
			'INSTITUTO DE INVESTIGACIONES AGROPECUARIAS',
			'INSTITUTO DE NUTRICIÓN Y TECNOLOGÍA DE LOS ALIMENTOS',
			'INSTITUTO DE SALUD PÚBLICA DE CHILE',
			'INSTITUTO DE SISTEMAS COMPLEJOS DE VALPARAISO',
			'INSTITUTO FORESTAL',
			'INSTITUTO LATINOAMERICANO DE DOCTRINA Y ESTUDIOS SOCIALES',
			'INSTITUTO SISTEMAS COMPLEJOS DE INGENIERÍA',
			'INSTITUTO SUPERIOR DE ARTES Y CIENCIAS SOCIALES',
			'MUSEO CHILENO DE ARTE PRECOLOMBINO',
			'MUSEO NACIONAL DE HISTORIA NATURAL',
			'OTRA',
			'PROGRAMA DE ECONOMÍA DEL TRABAJO',
			'PROGRAMA INTERDISCIPLINARIO INVESTIGACIÓN EN EDUCACIÓN',
			'SERVICIO NACIONAL DE GEOLOGÍA Y MINERÍA',
			'UNIVERSIDAD ACADEMIA DE HUMANISMO CRISTIANO',
			'UNIVERSIDAD ADOLFO IBAÑEZ',
			'UNIVERSIDAD ADVENTISTA DE CHILE',
			'UNIVERSIDAD ALBERTO HURTADO',
			'UNIVERSIDAD ANDRES BELLO',
			'UNIVERSIDAD ARTURO PRAT',
			'UNIVERSIDAD AUTRAL DE CHILE',
			'UNIVERSIDAD AUTÓNOMA DE CHILE',
			'UNIVERSIDAD BERNARDO O\'HIGGINS',
			'UNIVERSIDAD BOLIVARIANA',
			'PONTIFICIA UNIVERSIDAD CATÓLICA DE CHILE',
			'UNIVERSIDAD CATÓLICA DE LA SANTISIMA CONCEPCIÓN',
			'UNIVERSIDAD CATÓLICA DE TEMUCO',
			'UNIVERSIDAD CATÓLICA DEL MAULE',
			'UNIVERSIDAD CATÓLICA DEL NORTE',
			'UNIVERSIDAD CATÓLICA SILVA HENRIQUEZ',
			'UNIVERSIDAD CENTRAL DE CHILE',
			'UNIVERSIDAD CHILENO BRITÁNICA',
			'UNIVERSIDAD DE ACONCAGUA',
			'UNIVERSIDAD DE ANTOFAGASTA',
			'UNIVERSIDAD DE ARTES Y CIENCIAS SOCIALES - UARCIS',
			'UNIVERSIDAD DE ATACAMA',
			'UNIVERSIDAD DE CIENCIAS DE LA INFORMÁTICA',
			'UNIVERSIDAD DE CONCEPCIÓN',
			'UNIVERSIDAD DE CHILE',
			'UNIVERSIDAD DE LA FRONTERA',
			'UNIVERSIDAD DE LA SERENA',
			'UNIVERSIDAD DE LAS AMÉRICAS',
			'UNIVERSIDAD DE LOS ANDES',
			'UNIVERSIDAD DE LOS LAGOS',
			'UNIVERSIDAD DE MAGALLANES',
			'UNIVERSIDAD DE PLAYA ANCHA DE CIENCIAS DE LA EDUCACIÓN',
			'UNIVERSIDAD DE SANTIAGO DE CHILE',
			'UNIVERSIDAD DE TALCA',
			'UNIVERSIDAD DE TARAPACÁ',
			'UNIVERSIDAD DE VALPARAÍSO',
			'UNIVERSIDAD DE VIÑA DEL MAR',
			'UNIVERSIDAD DEL BIO BIO',
			'UNIVERSIDAD DEL DESARROLLO',
			'UNIVERSIDAD DEL MAR',
			'UNIVERSIDAD DEL PACÍFICO',
			'UNIVERSIDAD DIEGO PORTALES',
			'UNIVERSIDAD FINIS TERRAE',
			'UNIVERSIDAD GABRIELA MISTRAL',
			'UNIVERSIDAD IBEROAMERICANA DE CIENCIAS Y TECNOLOGÍAS',
			'UNIVERSIDAD INTERNACIONAL SEK',
			'UNIVERSIDAD MAYOR',
			'UNIVERSIDAD METROPOLITANA DE CIENCIAS DE LA EDUCACIÓN UMCE',
			'UNIVERSIDAD MIGUEL DE CERVANTES',
			'UNIVERSIDAD PEDRO DE VALDIVIA',
			'UNIVERSIDAD REGIONAL SAN MARCOS',
			'UNIVERSIDAD SAN SEBASTIÁN',
			'UNIVERSIDAD SANTO TOMÁS',
			'UNIVERSIDAD TÉCNICA FEDERICO SANTA MARÍA',
			'UNIVERIDAD TECNOLÓGICA DE CHILE INACAP',
			'UNIVERSIDAD TECNOLÓGICA METROPOLITANA UTEM',
			'UNIVERSIDAD UNIACC, DE ARTES, CIENCIAS Y COMUNICACIÓN',
			'UNIVERSIDAD CATÓLICA DE VALPARAÍSO'
		]
	end

	def lgen_sectores_economicos
		[
			'Actividades empresariales',
			'Acuicultura',
			'Agricultura',
			'Alimentos procesados y bebidas no alcoholicas',
			'Apicultura',
			'Biotecnología',
			'Capital humano',
			'Comercio',
			'Comunicaciones',
			'Construcción',
			'Educación',
			'Energía',
			'Enseñanza',
			'Financiero',
			'Floricultura',
			'Forestal',
			'Fruticultura',
			'Hoteles',
			'Industrias creativas (Audio-Visuales-Literatura)',
			'Logística',
			'Manufactura metalmecánica',
			'Medicina y salud humana',
			'Medio ambiente',
			'Minería',
			'Otras manofacturas (vidrio, plástico, tabaco, textil, etc.)',
			'Otro',
			'Pecuario',
			'Pesca artesanal',
			'Pesca industrial',
			'Sector público',
			'Servicios financieros y empresariales',
			'Silvicultura',
			'Sustancias químicas',
			'TIC\'s',
			'Transporte',
			'Turismo',
			'Vitivinícola'
		]
	end

	def lgen_alcances
		[
			'Nacional',
			'Internacional'
		]
	end

	def lgen_financiamientos
		[
			'Fondos ICM',
			'Adscrito',
			'Financiamiento Externo',
			'Mixto (ICM + Externo)'
		]
	end

	def lgen_categorias
		[
			'ISI/WOS o Similar a ISI/WOS standard',
			'SCIELO o Similar a SCIELO standard',
			'Libros y Capítulos de Libros',
			'Otras Publicaciones',
			'Scopus'
		]
	end
end