class Investigador < ApplicationRecord

	REGIONES = [
		'Arica y Parinacota',
		'Tarapacá',
		'Antofagasta',
		'Atacama',
		'Coquimbo',
		'Valparaiso',
		'Libertador General Bernardo O\'Higgins',
		'Maule',
		'Bío Bío',
		'de la Araucanía',
		'de los Lagos',
		'Aisén del General Carlos Ibañez del Campo',
		'Magallanes y Antártica Chilena',
		'Metropolitana de Santiago',
		'de los Rios'
	]

	NACIONALIDADES = [
		'Afgano',
		'Albanés',
		'Alemán',
		'Americano / Noreteamericano',
		'Andorrano',
		'Angoleño',
		'Anguilense',
		'Antiguano',
		'Antillano holandés',
		'Argelino',
		'Argentino',
		'Armenio',
		'Arubeño',
		'Australiano',
		'Austríaco',
		'Azerbaiyano, Azerí',
		'Bahamés, Bahameño',
		'Bahreini',
		'Bangladesí',
		'Barbadense, Barbadiño',
		'Belga',
		'Beliceño',
		'Beninés',
		'Bermudeño',
		'Bielorruso',
		'Birmano',
		'Boliviano',
		'Bosnio, Bosnioherzegovino',
		'Botsuano',
		'Brasileño',
		'Británico',
		'Bruneano',
		'Búlgaro',
		'Burkinés',
		'Burundés',
		'Butanés',
		'Caboverdiano',
		'Caimanés',
		'Camboyabo/na',
		'Camerunés',
		'Canadiense',
		'Centroafricano',
		'Chadiano',
		'Checo',
		'Chileno',
		'Chino',
		'Chipriota',
		'Cingalés, Esrilanqués',
		'Colombiano',
		'Comorense',
		'Congolés, Congoleño',
		'Costarricense',
		'Croata',
		'Cubano',
		'Curazaleño',
		'Danés',
		'Djibutí, Djibutiense',
		'Dominicano',
		'Dominiqués',
		'Ecuatoguineano',
		'Ecuatoriano',
		'Egipcio',
		'Emiratí',
		'Eritreo',
		'Escocés',
		'Eslovaco',
		'Esloveno',
		'Español',
		'Estonio',
		'Etíope',
		'Feroés',
		'Filipino',
		'Finlandés',
		'Fiyiano',
		'Francés',
		'Gabonés',
		'Galés',
		'Gambiano',
		'Georgiano',
		'Gerogiano',
		'Ghanés',
		'Gibraltareño',
		'Granadino',
		'Griego',
		'Guamés',
		'Guatemalteco',
		'Guerneseyés',
		'Guineano',
		'Guyanés',
		'Haitiano',
		'Holandés',
		'Hondureño',
		'Húngaro',
		'Indio',
		'Indonesio',
		'Iraní / persa',
		'Iraquí',
		'Irlandés',
		'Islandes',
		'Israelí',
		'Italiano',
		'Jamaicano',
		'Japonés',
		'Jerseyés',
		'Jordano',
		'Kasajo, Kasako',
		'Keniano',
		'Kirguís, Kirguiso',
		'Kiribatiano',
		'Kosovar',
		'Kuwaití',
		'Laosiano',
		'Lesotense',
		'Letón',
		'Libanés',
		'Liberiano',
		'Libio',
		'Liechtensteiniano',
		'Lituano',
		'Luxemburgués',
		'Macaense',
		'Macedonio',
		'Malasio',
		'Malauí',
		'Maldivo',
		'Malgache',
		'Maliense, Malí',
		'Maltés',
		'Malvinense',
		'Marfileño',
		'Marroquí',
		'Marshalés',
		'Mauriciano',
		'Mauritano',
		'Mexicano',
		'Micronesio',
		'Moldavo',
		'Monegasco',
		'Mongol',
		'Montenegrino',
		'Montserratense',
		'Mozambiqueño',
		'Namibio',
		'Nauruano',
		'Neerlandés',
		'Neozelandés',
		'Nepalés',
		'Nicaraguense',
		'Nigeriano',
		'Nigerino',
		'Niueño',
		'Norcoreano',
		'Noruego',
		'Omaní, Omanés',
		'Otra',
		'Palauano',
		'Palestino',
		'Panameño',
		'Papú, Papúano',
		'Paquistaní',
		'Paraguayo',
		'Peruano',
		'Polaco',
		'Portugués',
		'Puertoriqueño',
		'Qatarí, Catarí',
		'Ruandés',
		'Rumano',
		'Ruso',
		'Saharaui',
		'Salomonense, Salomon',
		'Salvadoreño',
		'Samoano',
		'Sancristobaleño',
		'Santalucense',
		'Santotomense',
		'Sanvicentino',
		'Saudí',
		'Senegalés',
		'Serbio',
		'Seychellense',
		'Sierraleonés',
		'Singapurense',
		'Sirio',
		'Somalí',
		'Suazi',
		'Sudafricano',
		'Sudanés',
		'Sueco',
		'Suizo',
		'Surcoreano',
		'Surinamés',
		'Sursudanés',
		'Tailandés',
		'Taiwanés',
		'Tanzano',
		'Tayiko',
		'Timorense',
		'Togolés',
		'Tongano',
		'Trinitense, Tobaguense',
		'Tunecino',
		'Turco',
		'Turcomano',
		'Tuvaluano',
		'Ucraniano',
		'Ugandés',
		'Uruguayo',
		'Uzbeko',
		'Vanuatuense',
		'Venezolano',
		'Vietnamita',
		'Yemení, Yemenita',
		'Yibutiano',
		'Zambio, Zambés, Zambeño',
		'Zimbabuense'
	]

	CATEGORIAS = [
		'Investigador Responsable',
		'Investigador Responsable Suplente',
		'Investigador Adjunto',
		'Investigador Asociado',
		'Investigador Joven',
		'Investigador Senior',
		'Postdoctorante'
	]

	PROFESIONES = [
		'Administración de Empresas',
		'Administración Pública',
		'Agronomía',
		'Antropología',
		'Arqueología',
		'Arquitectura',
		'Astronomía',
		'Auditoría',
		'Bibliotecología',
		'Bioingeniería',
		'Biología',
		'Biología Marina',
		'Bioquímica',
		'Biotecnología',
		'Ciencias Políticas',
		'Cine',
		'Comunicación',
		'Comunicación Audiovisual',
		'Construcción Civil',
		'Contabilidad',
		'Derecho',
		'Diseño',
		'Diseño Gráfico',
		'Diseño Industrial',
		'Ecología Marina',
		'Economía',
		'Educación Básica',
		'Educación Media',
		'Educación Diferencial',
		'Educación Física',
		'Educación Parvularia',
		'Enfermería',
		'Estadística',
		'Filosofía',
		'Física',
		'Fonoaudiología',
		'Geofísica',
		'Geología',
		'Historia',
		'Informática',
		'Ingeniería',
		'Ingeniería Agronómica',
		'Ingeniería Ambiental',
		'Ingeniería Civil',
		'Ingeniería comercial',
		'Ingeniería de Ejecución',
		'Estudios internacionales',
		'Kinesiología',
		'Literatura',
		'Matemáticas',
		'Medicina',
		'Medicina Veterinaria',
		'Meteorología',
		'Nutrición',
		'Obstetricia',
		'Oceanografía',
		'Odontología',
		'Pedagogía',
		'Periodismo',
		'Psicología',
		'Psicopedagogía',
		'Psiquiatría',
		'Publicidad',
		'Química',
		'Química y Farmacia',
		'Relaciones Públicas',
		'Sociología',
		'Tecnología Médica',
		'Teología',
		'Terapia Ocupacional',
		'Topografía',
		'Trabajo Social',
		'Traducción',
		'Turismo',
		'Otra'
	]

	FINANCIAMIENTOS = [
		'Fondos ICM',
		'Adscrito',
		'Financiamiento Externo',
		'Mixto (ICM + Externo)'
	]

	RELACION_CENTRO = [
		'Full Time',
		'Part Time'
	]

	DISPLAY_FIELDS = [
		['tipo_documento',            'Tipo de Documento',                  'string'],
		['rut_pasaporte',             'Rut / Pasaporte',                    'string'],
		['nombres',                   'Nombres',                            'string'],
		['paterno',                   'Apellido Paterno',                   'string'],
		['materno',                   'Apellido Materno',                   'string'],
		['direccion_correspondencia', 'Dirección Correspondencia',          'string'],
		['comuna',                    'Comuna',                             'string'],
		['region',                    'Región Correspondencia',             'string'],
		['fecha_nacimiento',          'Fecha de Nacimiento',                'datetime'],
		['nacionalidad',              'Nacionalidad',                       'string'],
		['genero',                    'Genero',                             'string'],
		['categoria',                 'Categoría',                          'string'],
		['horas_dedicacion',          'Horas Dedicación',                   'string'],
		['profesion',                 'Profesión',                          'string'],
		['grado_academicos',          'Grado Académico',                    'asociation'],
		['institucion',               'Institución a la que Pertenece',     'string'],
		['cargo',                     'Cargo Actual',                       'string'],
		['email',                     'E-mail',                             'string'],
		['telefono_1',                'Telefono 1',                         'string'],
		['telefono_2',                'Telefono 2',                         'string'],
		['celular',                   'Celular',                            'string'],
		['linea_investigaciones',     'Lineas de Investigación Vinculadas', 'asociation'],
		['disciplinas',               'Disciplinas Vinculadas',             'asociation'],
		['fuente_financiamiento',     'Fuente de Financiamiento',           'string'],
		['relacion_centro',           'Relación con Centro',                'string'],
		['fecha_inicio',              'Fecha de Inicio',                    'datetime'],
		['fecha_termino',             'Fecha de Término',                   'datetime'],
		['vigencia',                  'Vigencia',                           'string']
	]

	TABLA_FIELDS = [
		['investigador', 'show'],
		['propietario',  'normal']
	]

	has_many :i_gas
	has_many :grado_academicos, through: :i_gas

	has_many :i_lis
	has_many :linea_investigaciones, through: :i_lis

	has_many :i_dis
	has_many :disciplinas, through: :i_dis

	has_many :pis
	has_many :publicaciones, through: :pis

	has_many :pc_is
	has_many :presentacion_congresos, through: :pc_is

	has_many :ci_is
	has_many :comite_editoriales, through: :ci_is

	has_many :fj_is
	has_many :formacion_jovenes, through: :fj_is

	has_many :rfc_as
	has_many :rfa_colaboraciones, through: :rfc_as, source: 'rf_colaboracion', foreign_key: 'rf_colaboracion_id'

	has_many :rfc_is
	has_many :rfi_colaboraciones, through: :rfc_is, source: 'rf_colaboracion', foreign_key: 'rf_colaboracion_id'

	has_many :rc_is
	has_many :r_colaboraciones, through: :rc_is

	has_many :ad_is
	has_many :actividad_difusiones, through: :ad_is

	has_many :pp_is
	has_many :producto_pmes, through: :pp_is

	has_many :ae_is
	has_many :articulo_entrevistas, through: :ae_is

	validates :email, presence: true
	validates :email, uniqueness: true

	def investigador
		"#{self.nombres} #{self.paterno} #{self.materno}"
	end

end
